"""Added Task Type Field in the taskmodel

Revision ID: 5be339094e55
Revises: ce7aea4804eb
Create Date: 2026-04-04 15:59:29.165998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
 

# revision identifiers, used by Alembic.
revision: str = '5be339094e55'
down_revision: Union[str, None] = 'ce7aea4804eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_type', sa.String(), server_default='Agent', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'task_type')
    # ### end Alembic commands ###