"""Schema Change in the Message Model

Revision ID: a897535e6ed5
Revises: 5be339094e55
Create Date: 2026-04-08 11:09:53.709089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
 

# revision identifiers, used by Alembic.
revision: str = 'a897535e6ed5'
down_revision: Union[str, None] = '5be339094e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('msg_type', sa.String(), server_default='text', nullable=False))
    op.add_column('messages', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.drop_index(op.f('ix_messages_agent_id'), table_name='messages')
    op.create_unique_constraint('uq_messages_workflow_idempotency', 'messages', ['workflow_id', 'idempotency_key'])
    op.drop_column('messages', 'agent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_messages_workflow_idempotency', 'messages', type_='unique')
    op.create_index(op.f('ix_messages_agent_id'), 'messages', ['agent_id'], unique=False)
    op.drop_column('messages', 'idempotency_key')
    op.drop_column('messages', 'metadata_json')
    op.drop_column('messages', 'msg_type')
    # ### end Alembic commands ###