"""Change in Schema of WorkflowModel

Revision ID: ce7aea4804eb
Revises: 0aef1bf0038a
Create Date: 2026-04-04 11:43:42.442576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce7aea4804eb'
down_revision: Union[str, None] = '0aef1bf0038a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dependencies',
    sa.Column('upstream_task_id', sa.Uuid(), nullable=False),
    sa.Column('downstream_task_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['downstream_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upstream_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('upstream_task_id', 'downstream_task_id')
    )
    op.drop_column('tasks', 'depends_on')
    op.add_column('workflows', sa.Column('global_context', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'global_context')
    op.add_column('tasks', sa.Column('depends_on', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('task_dependencies')
    # ### end Alembic commands ###